### ISSUE TITLE
嘿，伙计，你想要知道Issues的提交规范吗？

### ISSUE THREAD

**Issue by Drenayo** [Drenayo/UnityGameSamples#1]
哦，是的，我非常想要知道这些东西，请问你能告诉我吗？

哦，是的，我非常乐意，你参考标签就行了。

**Comment by hui123456-pixel** [comment]
这个标签怎么加,第一次用,这个标签怎么加不了?

**Comment by Drenayo** [comment]
> 这个标签怎么加,第一次用,这个标签怎么加不了?

**
![image](https://github.com/Drenayo/UnityGameSamples/assets/92071969/d391f735-f79d-45fd-b753-7a481d33605f)
**

**Comment by hui123456-pixel** [comment]
我这边不显示这个按钮

**Comment by hui123456-pixel** [comment]
![Uploading 1.jpg…]()
我这边是这样的

**Comment by Drenayo** [comment]
> 我这边不显示这个按钮

问题不大，可能只有我有权限，那我自己分类就行了，反正issues也不多

**Comment by hui123456-pixel** [comment]
<img width="980" alt="1" src="https://github.com/Drenayo/UnityGameSamples/assets/173898314/d28b8558-a568-4618-9c1e-7c848d9b67ed">

**Comment by hui123456-pixel** [comment]
好的好的
