### ISSUE TITLE
您好，可以解释一下怎么使用吗？

### ISSUE THREAD

**Issue by fishmisswater** [Drenayo/UnityGameSamples#2]
Library\PackageCache\com.unity.postprocessing@2.0.3-preview\PostProcessing\Runtime\PostProcessManager.cs(424,66): error CS0117: “EditorSceneManager”未包含“IsGameObjectInScene”的定义

![image](https://github.com/Drenayo/UnityGameSamples/assets/11415507/214faf22-8457-4af2-b7ef-0b524bc85fdd)
点击运行报错了，网上说删掉PostProcessManager这个文件夹重启，但是我这边没用，不知道怎么解决

**Comment by Drenayo** [comment]
你这个是Unity后处理的包，和我的项目没有关系，如果你始终无法解决这个问题，可以试着新建一个项目，新建一个场景，然后新建一个脚本，找到文本打字机的代码，粘贴过去。
